{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    # In production this Secret is managed by Vault Agent Injector — not Helm
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
