plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  tag:Project: shopflow
  instance-state-name: running

keyed_groups:
  - key: tags.Role
    prefix: role
    separator: "_"
  - key: tags.Role
    prefix: ""
    separator: ""
  - key: tags.Environment
    prefix: env
    separator: "_"

hostnames:
  - dns-name

compose:
  ansible_host: public_ip_address
