replicaCount: 1
image:
  tag: "716ad7b0fad226136f3f810538b814eadc9053ef"
ingress:
  enabled: true
  hosts:
    - host: dev.shopflow.example.com
      paths:
        - path: /api/products
          pathType: Prefix
config:
  DB_HOST: "shopflow-dev-postgres.cifsu6igghrp.us-east-1.rds.amazonaws.com"
  NODE_ENV: "development"
hpa:
  enabled: false
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
