replicaCount: 1
image:
  tag: "f57d8745711f409a009dcb38e875a5ea6ccee373"
ingress:
  enabled: true
  hosts:
    - host: dev.shopflow.example.com
      paths:
        - path: /api/orders
          pathType: Prefix
config:
  DB_HOST: "shopflow-dev-postgres.cifsu6igghrp.us-east-1.rds.amazonaws.com"
  NODE_ENV: "development"
hpa:
  enabled: false
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
