sonar.projectKey=shopflow-order-service
sonar.projectName=ShopFlow Order Service
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-report.xml

sonar.qualitygate.wait=true
