replicaCount: 1
image:
  tag: "ab998ca6e53a1c1cfb51f87fc18b859c48e8a1e2"
ingress:
  enabled: true
  hosts:
    - host: dev.shopflow.example.com
      paths:
        - path: /
          pathType: Prefix
hpa:
  enabled: false
resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi
