replicaCount: 1
image:
  tag: "f57d8745711f409a009dcb38e875a5ea6ccee373"
ingress:
  enabled: true
  hosts:
    - host: dev.shopflow.example.com
      paths:
        - path: /
          pathType: Prefix
hpa:
  enabled: false
resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi
