replicaCount: 1

image:
  repository: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/shopflow/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: shopflow.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

serviceAccount:
  create: true
  name: ""
  annotations: {}

fullnameOverride: ""
