replicaCount: 1
image:
  tag: "59f0b20c0ab72d49bde7eb2a3e7e96a6561e0367"
ingress:
  enabled: true
  hosts:
    - host: dev.shopflow.example.com
      paths:
        - path: /
          pathType: Prefix
hpa:
  enabled: false
resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi
